### ISSUE TITLE
Died at .../bin/sizeme_store.pl line 299, <> line 5.

### ISSUE THREAD

**Issue by sni** [timbunce/devel-sizeme#18]
i tried the latest git head and cannot store to sqlite anymore:

I get this error:

Died at .../bin/sizeme_store.pl line 299, <> line 5.
Segmentation fault (core dumped)

Line 299 is:
my $node = $seqn2node{$id} || die;

If i dump the complete line, it is:
6 0 166946456 (null)

**Comment by timbunce** [comment]
On Fri, Oct 04, 2013 at 04:21:33AM -0700, Sven Nierlein wrote:

>    Died at .../bin/sizeme_store.pl line 299, <> line 5.
>    Segmentation fault (core dumped)
> 
>    If i dump the complete line, it is:
>    6 0 166946456 (null)

Yeap. There's a bug with perl built with the use64bitint option.
(The use64bitall option works.)

Tim.
